=== nerimoe/crouton/adhd/cras/src/common/third_party/dbus/introspect.dtd
<!-- DTD for D-Bus Introspection data -->
<!-- (C) 2005-02-02 David A. Wheeler; released under the D-Bus licenses,
         GNU GPL version 2 (or greater) and AFL 1.1 (or greater) -->

<!-- see D-Bus specification for documentation -->

<!-- This file originates from https://github.com/freedesktop/dbus/blob/master/doc/introspect.dtd
     modidified for CRAS to support tp:docstring -->

<!ELEMENT node (node|interface)*>
<!ATTLIST node xmlns:tp CDATA #IMPLIED>
<!ATTLIST node name CDATA #IMPLIED>

<!ELEMENT interface (method|signal|property|annotation)*>
<!ATTLIST interface name CDATA #REQUIRED>

<!ELEMENT method (arg|annotation|tp:docstring)*>
<!ATTLIST method name CDATA #REQUIRED>

<!ELEMENT signal (arg|annotation|tp:docstring)*>
<!ATTLIST signal name CDATA #REQUIRED>

<!ELEMENT arg (annotation|tp:docstring)*>
<!ATTLIST arg name CDATA #REQUIRED>
<!ATTLIST arg type CDATA #REQUIRED>
<!-- Method arguments SHOULD include "direction",
     while signal and error arguments SHOULD not (since there's no point).
     The DTD format can't express that subtlety. -->
<!ATTLIST arg direction (in|out) "in">

<!-- AKA "attribute" -->
<!ELEMENT property (annotation)*>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property type CDATA #REQUIRED>
<!ATTLIST property access (read|write|readwrite) #REQUIRED>

<!ELEMENT annotation EMPTY>  <!-- Generic metadata -->
<!ATTLIST annotation name CDATA #REQUIRED>
<!ATTLIST annotation value CDATA #REQUIRED>

<!ELEMENT tp:docstring (#PCDATA)>

=== nerimoe/crouton/adhd/cras/dbus_bindings/org.chromium.cras.Telephony.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  Copyright 2021 The ChromiumOS Authors
  Use of this source code is governed by a BSD-style license that can be
  found in the LICENSE file.
-->
<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"https://chromium.googlesource.com/chromiumos/third_party/adhd/+/refs/heads/main/cras/dbus_bindings/introspect.dtd">
<node>
  <interface name="org.chromium.cras.Telephony">
    <method name="AnswerCall">
    </method>
    <method name="IncomingCall">
      <arg name="value" type="s" direction="in"/>
    </method>
    <method name="TerminateCall">
    </method>
    <method name="SetBatteryLevel">
      <arg name="value" type="i" direction="in"/>
    </method>
    <method name="SetSignalStrength">
      <arg name="value" type="i" direction="in"/>
    </method>
    <method name="SetServiceAvailability">
      <arg name="value" type="i" direction="in"/>
    </method>
    <method name="SetDialNumber">
      <arg name="value" type="s" direction="in"/>
    </method>
    <method name="SetCallheld">
      <arg name="value" type="i" direction="in"/>
    </method>
    <method name="SetCallsetup">
      <arg name="value" type="i" direction="in"/>
    </method>
    <method name="SetCall">
      <arg name="value" type="i" direction="in"/>
    </method>
  </interface>
  <interface name="org.freedesktop.DBus.Introspectable">
    <method name="Introspect">
      <arg name="data" type="s" direction="out"/>
    </method>
  </interface>
</node>
